

// this file is autogenerated. do not make changes manually
using Microsoft.AspNetCore.Mvc;
using ProductManagerDatabase.Database;

namespace ProductManagerRest.GeneratedEndpoints
{

    public static partial class Config
    {

        static partial void GetAll<T>(ProductManagerContext dbContext)
        {

        }

        static partial void Get<T>(int id, ProductManagerContext dbContext)
        {

        }

        static partial void Create<T>( T entity)
        {

        }

        static partial void Update<T>(int id, T entity)
        {

        }

        static partial void Delete<T>(int id, ProductManagerContext dbContext)
        {

        }

    }

}